CREATE TABLE IF NOT EXISTS CUSTOMER (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    fone VARCHAR(20) NOT NULL,
    cnpj VARCHAR(30) NOT NULL UNIQUE,
    company_regular BOOLEAN NOT NULL
);
