INSERT INTO address (cep, state, city, neighborhood, road, house_number) 
VALUES 
(12345678, 'São Paulo', 'São Paulo', 'Centro', 'Rua da Consolação', '123'),
(23456789, 'Rio de Janeiro', 'Rio de Janeiro', 'Copacabana', 'Avenida Atlântica', '456'),
(34567890, 'Minas Gerais', 'Belo Horizonte', 'Savassi', 'Rua Pernambuco', '789'),
(45678901, 'Bahia', 'Salvador', 'Pelourinho', 'Rua do Carmo', '101'),
(56789012, 'Paraná', 'Curitiba', 'Centro', 'Rua XV de Novembro', '202'),
(67890123, 'Santa Catarina', 'Florianópolis', 'Lagoa da Conceição', 'Avenida das Rendeiras', '303'),
(78901234, 'Rio Grande do Sul', 'Porto Alegre', 'Moinhos de Vento', 'Rua Padre Chagas', '404'),
(89012345, 'Distrito Federal', 'Brasília', 'Asa Sul', 'Eixo Monumental', '505'),
(90123456, 'São Paulo', 'Campinas', 'Vila Proost de Souza', 'Rua José de Alencar', '606'),
(12309876, 'Paraná', 'Londrina', 'Centro', 'Rua Rio Branco', '707');
